# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-1'

menu:
- {name: 'About',   url: 'about.html'}
- {name: 'Projects', url: 'projects.html'}
- {name: 'CV', url: 'cv.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://www.github.com/shreyasriram4'}
- {icon: 'linkedin',   link: 'http://www.linkedin.com/in/shreyasriram4/'}
- {icon: 'envelope',   link: 'mailto:shreyasriram4@gmail.com'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
